name: secret leak test

on:
  push:
    branches: [ master ]

jobs:
  secret-leak-test:
    runs-on: windows-latest

    steps:
    - name: Echo the secret
      run: |
        echo ${{ secrets.secret }}
        echo ${{ secrets.secret }} | sed 's/./& /g'
